apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: default-backend-rs
  name: default-backend-rs
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-backend-rs
  template:
    metadata:
      labels:
        app: default-backend-rs
    spec:
      containers:
      - image: petergrace/default-backend-rs:latest
        name: default-backend-rs
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        securityContext:
          readOnlyRootFilesystem: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
