apiVersion: v1
kind: Service
metadata:
  labels:
    app: default-backend-rs
  name: default-backend-rs
  namespace: nginx-ingress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: default-backend-rs
  type: ClusterIP
